sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda install conda-build
  - conda info -a
  - pip install flake8
  - git clone https://github.com/qiime2/q2lint
script:
  - flake8
  - python q2lint/q2lint.py
  - conda build -c https://conda.anaconda.org/qiime2 -c defaults --override-channels --python $PYTHON_VERSION ci/recipe
