sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n test-env python=$PYTHON_VERSION nose 'setuptools<20.5.0' decorator pandas
  - source activate test-env
  - pip install flake8
  - pip install .
  - git clone https://github.com/qiime2/q2lint
script:
  # TODO don't require devs to remember setting this env var before running
  # tests. The value can be anything.
  - QIIMETEST= nosetests
  - flake8
  - python q2lint/q2lint.py
