dist: trusty
sudo: false
language: python
before_install:
  - export MPLBACKEND='Agg'
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a
  - git clone https://github.com/qiime2/q2lint ../q2lint
install:
  - conda create -q -n test-env --file https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-conda-linux-64.txt
  - source activate test-env
  - pip install -q flake8
  - conda install nose
  - python setup.py install
script:
  - flake8
  - python ../q2lint/q2lint.py
  - QIIMETEST= nosetests
